<div class="nav-section-left">
    <div class="nav-section-filter">
        <div class="nav-section-item">
            <a href="#!" data-pushbar-target="left" class="hum_menu">
                <img src="<?= $block->getViewFileUrl('images/HamburgerMenu.png') ?>"
                    alt="menu" width="33" height="21" style="height: auto;"></a>
        </div>
        <div class="nav-section-dropdown">
            <select name="" id="">
                <option value="">How do you want your items?</option>
            </select>
        </div>
    </div>
    <aside data-pushbar-id="left" data-pushbar-direction="left" class="">
        <div class="navigation">
            <div class="close_side_bar" data-pushbar-close="">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokewidth="1.5"
                    stroke="currentColor" classname="w-6 h-6">
                    <path strokelinecap="round" strokelinejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                </svg>
            </div>
            <ul class="nav_bar">
                <li class="nav_list"> <a href="#!" class="nav_item">Pizza</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Cakes</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Biscuits</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Pastry</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Bread</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Puffs</a></li>
            </ul>
            <ul class="nav_bar category">
                <li class="nav_list"> <a href="#!" class="nav_item">What’s new</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Best sellers</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Quick order</a></li>
                <li class="nav_list"> <a href="#!" class="nav_item">Contact</a></li>
            </ul>
        </div>
    </aside>

</div>