<div class="email_row">
    <div class="title_block">
        <h2>Enter the world of Tehzeeb</h2>
        <p>News, Bakery Creation & Latest events in stores.</p>
    </div>

    <form class="newsletter-form" action="<?= $block->getFormActionUrl() ?>" method="post">
        <div class="email_field">
            <div class="input_field">
                <input type="email" name="email" placeholder="Enter your email address" required style="background: ;" />
            </div>

            <button type="submit" class="footer_Cta primary_cta">
                Subscribe
            </button>
        </div>
    </form>
</div>